baseURL = "shwetarkadam.github.io"
languageCode = "en-us"
title = "Shweta's Braindump Z"
theme = "cortex-dark"
pygmentsStyle = "dracula"

[params]
email = "shwetakadam.portfolio@gmail.com"
footer = "Icon by Freepik. Built with â™¥ with Org-mode and Hugo."
entrypoint= "/about"
repo = "https://github.com/shwetarkadam/braindump"
